name: emotion_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  fl_chart: 0.60.0
  font_awesome_flutter: 10.4.0
  flutter_easyloading: 3.0.5
  modal_bottom_sheet: 3.0.0-pre
  google_fonts: 4.0.3
  shimmer: 2.0.0
  uuid: 3.0.7
  intl: 0.18.0
  supabase_flutter: 1.4.0
  get_storage: 2.0.3
  image_picker: 0.8.6+4
  url_launcher: 6.1.10
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.19

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: "assets/images/logo.png"
  android: true
  ios: true

flutter_native_splash:
  color: "#43A047"
  image: assets/images/logo.png

  android_12:
    image: assets/images/logo.png
    icon_background_color: "#43A047"

flutter:
  assets:
    - assets/images/
  uses-material-design: true
